<<<<<<< HEAD


import os
=======
"""
Django settings for pollster project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import django_heroku
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
=======
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1^_&3^e5&d&^1r)7q21ku7kif0czi07fiw_1^&ref^k!y#_h-d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = []
=======
ALLOWED_HOSTS = ['*']
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d


# Application definition

INSTALLED_APPS = [
<<<<<<< HEAD
    'polls.apps.PollsConfig',
=======
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'users.apps.UsersConfig',
    'crispy_forms',
    'django_cleanup.apps.CleanupConfig',
    'friends',
]

=======
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'polls',
    'widget_tweaks',
    'users',
    'api',
]

AUTH_USER_MODEL = 'users.CustomUser'

>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pollster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pollster.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
<<<<<<< HEAD
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
=======
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
=======
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.AllowAny',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [ # new
        'rest_framework.authentication.TokenAuthentication', # new
        'rest_framework.authentication.SessionAuthentication', # new
],
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

<<<<<<< HEAD

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'index'

LOGIN_URL = 'login'

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
=======
BOOTSTRAP4 = { 'include_jquery': True }

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
django_heroku.settings(locals())
>>>>>>> dd8e683bf902422332c15d70d55d3d53b3553e2d
