# Generated by Django 3.1.1 on 2021-04-22 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210413_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
